apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grass-gis
  name: grass-gis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grass-gis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/rb-road-network-rb-roads-network: "true"
        io.kompose.service: grass-gis
    spec:
      containers:
        - env:
            - name: DISPLAY
              value: :0
          image: osgeo/grass-gis:releasebranch_8_3-ubuntu_wxgui
          name: grass-gis
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /root/grassdata
              name: grass-gis-hostpath0
            - mountPath: /tmp/.X11-unix
              name: grass-gis-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/robertc/grassdata
          name: grass-gis-hostpath0
        - hostPath:
            path: /tmp/.X11-unix/
          name: grass-gis-hostpath1
status: {}
