apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rb-roads-api
  name: rb-roads-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rb-roads-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/rb-road-network-rb-roads-network: "true"
        io.kompose.service: rb-roads-api
    spec:
      containers:
        - image: rb-roads-api:latest
          name: rb-roads-api
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: rb-roads-api-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: rb-roads-api-hostpath0
status: {}
