apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rb-roads
  name: rb-roads
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rb-roads
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/rb-road-network-rb-roads-network: "true"
        io.kompose.service: rb-roads
    spec:
      containers:
        - command:
            - /home/appuser/rb_app/justPop.exe
          image: rb-roads:latest
          name: rb-roads
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /home/appuser/rb_data
              name: rb-roads-hostpath0
            - mountPath: /home/appuser/rb_app/logs
              name: rb-roads-hostpath1
            - mountPath: /home/appuser/rb_app/output
              name: rb-roads-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/robertc/Documents/rb_data
          name: rb-roads-hostpath0
        - hostPath:
            path: /home/robertc/Git/rb-road-network/logs
          name: rb-roads-hostpath1
        - hostPath:
            path: /home/robertc/Git/rb-road-network/output
          name: rb-roads-hostpath2
status: {}
